package com.example.smiti.model;

import com.google.gson.annotations.SerializedName;

public class Todo {
    @SerializedName("id")
    private int todoId;

    @SerializedName("user_email")
    private String userEmail;

    @SerializedName("task")
    private String task;

    @SerializedName("due_date")
    private String dueDate; // YYYY-MM-DD 형식

    @SerializedName("is_completed")
    private boolean isCompleted;

    // Constructor
    public Todo(int todoId, String userEmail, String task, String dueDate, boolean isCompleted) {
        this.todoId = todoId;
        this.userEmail = userEmail;
        this.task = task;
        this.dueDate = dueDate;
        this.isCompleted = isCompleted;
    }

    // Constructor for adding new todo (id will be generated by server)
    public Todo(String userEmail, String task, String dueDate) {
        this.userEmail = userEmail;
        this.task = task;
        this.dueDate = dueDate;
        this.isCompleted = false; // Default to not completed for new tasks
    }

    // Getters
    public int getTodoId() {
        return todoId;
    }

    public String getUserEmail() {
        return userEmail;
    }

    public String getTask() {
        return task;
    }

    public String getDueDate() {
        return dueDate;
    }

    public boolean isCompleted() {
        return isCompleted;
    }

    // Setters (if needed for updates, especially for isCompleted)
    public void setTodoId(int todoId) {
        this.todoId = todoId;
    }

    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    public void setTask(String task) {
        this.task = task;
    }

    public void setDueDate(String dueDate) {
        this.dueDate = dueDate;
    }

    public void setCompleted(boolean completed) {
        isCompleted = completed;
    }

    @Override
    public String toString() {
        return "Todo{" +
               "todoId=" + todoId +
               ", userEmail='" + userEmail + "'" +
               ", task='" + task + "'" +
               ", dueDate='" + dueDate + "'" +
               ", isCompleted=" + isCompleted +
               "}";
    }
} 